#!/bin/bash

INTERFACE="wlp3s0"

state="$(cat /sys/class/net/$INTERFACE/operstate)"

if [ "$state" != "up" ]
then
  echo ""
  echo ""
  echo "#ff0000"
  exit 0
fi

ssid=$(/sbin/iw dev $INTERFACE link | grep SSID | cut -d ":" -f 2)
rxspeed=$(/sbin/iw dev $INTERFACE link | grep "rx bitrate" | cut -d " " -f 3)

ipaddr="$(ip addr show $INTERFACE | perl -n -e'/inet (.+)\// && print $1')"
ipaddr="${ipaddr:-0.0.0.0}"

# full text
echo "$ipaddr ($rxspeed Mbits/s) $ssid"
#short text
echo ""
#color
echo "#00ff00"
