#! /bin/bash
 
SLEEP_TIME=5   # Default time between checks.
SAFE_PERCENT=30  # Still safe at this level.
DANGER_PERCENT=15  # Warn when battery at this level.
CRITICAL_PERCENT=7  # Final Notice when battery at this level.
HIBERNATE_PERCENT=5 #Hibernate at this level

export DISPLAY=:0.0
 
while [ true ]; do
    if [[ -n $(acpi -b | grep -i discharging) ]]; then
        pm-powersave true
        rem_bat=$(acpi -b | grep -Eo "[0-9]+%" | grep -Eo "[0-9]+")
 
        if [[ $rem_bat -gt $SAFE_PERCENT ]]; then
            SLEEP_TIME=10
        else
            SLEEP_TIME=5
            if [[ $rem_bat -le $DANGER_PERCENT ]]; then
                SLEEP_TIME=2
                notify-send -u critical -c battery "Battery Low" "$rem_bat% Remaining"
            fi
            if [[ $rem_bat -le $CRITICAL_PERCENT ]]; then
                SLEEP_TIME=2
		notify-send -u critical -c battery "Battery Critical" "Hibernating now"
            fi
	    if [[ $rem_bat -le $HIBERNATE_PERCENT ]]; then
                SLEEP_TIME=2
                pm-hibernate
            fi
        fi
    else
        pm-powersave false
        SLEEP_TIME=10
    fi
 
    sleep ${SLEEP_TIME}m
 
done
