#!/bin/sh
xrandr --output eDP1 --mode 1920x1080 --pos 1920x0 --rotate normal --output HDMI3 --off --output HDMI2 --mode 1920x1080i --pos 0x0 --rotate normal --output HDMI1 --off --output DP2 --off --output DP1 --off
