#! /bin/bash
# get current keyboard brightness from UPower
current_state=$(dbus-send --type=method_call --print-reply=literal --system \
--dest="org.freedesktop.UPower" /org/freedesktop/UPower/KbdBacklight org.freedesktop.UPower.KbdBacklight.GetBrightness)
# strip leading 9 characters "   int32 "
current_state=${current_state:9}
min_brightness=0
# if the current keyboard brightness is greater than zero, decrement brightness by one
if [ $current_state -gt $min_brightness ] ; then 
dbus-send --type=method_call --print-reply=literal --system \
--dest="org.freedesktop.UPower" /org/freedesktop/UPower/KbdBacklight org.freedesktop.UPower.KbdBacklight.SetBrightness \
int32:$((current_state-1))
#notify-send "Keyboard brightness reset to $((current_state-1))"
#else
# if the keyboard brightness is already at zero, complain
#notify-send "Keyboard brightness already at zero"
fi
